version: "3"
services:
  frontend:
    image: frontend
    build:
      context: ./frontend
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./frontend:/frontend
      - ./frontend/node_modules:/frontend/node_modules
